# Generated by Django 3.2 on 2022-08-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_request_call_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='request_call_back',
            field=models.CharField(choices=[('REQUEST_CALL_BACK', 'Yes'), ('NO_REQUEST_CALL_BACK', 'No')], max_length=20),
        ),
    ]
